// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file user/v1/user.proto (package user.v1, syntax proto3)
/* eslint-disable */

import type {
  GenFile,
  GenMessage,
  GenService,
} from "@bufbuild/protobuf/codegenv1";
import {
  fileDesc,
  messageDesc,
  serviceDesc,
} from "@bufbuild/protobuf/codegenv1";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file user/v1/user.proto.
 */
export const file_user_v1_user: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChJ1c2VyL3YxL3VzZXIucHJvdG8SB3VzZXIudjEiXQoEVXNlchIKCgJpZBgBIAEoCRIRCgl1c2VyX25hbWUYAiABKAkSDQoFZW1haWwYAyABKAkSEwoLZGVzY3JpcHRpb24YBCABKAkSEgoKY3JlYXRlZF9hdBgFIAEoCSJgChBMaXN0VXNlcnNSZXF1ZXN0EhYKCXBhZ2Vfc2l6ZRgBIAEoBUgAiAEBEhcKCnBhZ2VfdG9rZW4YAiABKAlIAYgBAUIMCgpfcGFnZV9zaXplQg0KC19wYWdlX3Rva2VuImMKEUxpc3RVc2Vyc1Jlc3BvbnNlEhwKBXVzZXJzGAEgAygLMg0udXNlci52MS5Vc2VyEhwKD25leHRfcGFnZV90b2tlbhgCIAEoCUgAiAEBQhIKEF9uZXh0X3BhZ2VfdG9rZW4iHAoOR2V0VXNlclJlcXVlc3QSCgoCaWQYASABKAkiVgoRQ3JlYXRlVXNlclJlcXVlc3QSCgoCaWQYASABKAkSEQoJdXNlcl9uYW1lGAIgASgJEg0KBWVtYWlsGAMgASgJEhMKC2Rlc2NyaXB0aW9uGAQgASgJIo0BChFVcGRhdGVVc2VyUmVxdWVzdBIKCgJpZBgBIAEoCRIWCgl1c2VyX25hbWUYAiABKAlIAIgBARISCgVlbWFpbBgDIAEoCUgBiAEBEhgKC2Rlc2NyaXB0aW9uGAQgASgJSAKIAQFCDAoKX3VzZXJfbmFtZUIICgZfZW1haWxCDgoMX2Rlc2NyaXB0aW9uIh8KEURlbGV0ZVVzZXJSZXF1ZXN0EgoKAmlkGAEgASgJMrgCCgtVc2VyU2VydmljZRJCCglMaXN0VXNlcnMSGS51c2VyLnYxLkxpc3RVc2Vyc1JlcXVlc3QaGi51c2VyLnYxLkxpc3RVc2Vyc1Jlc3BvbnNlEjEKB0dldFVzZXISFy51c2VyLnYxLkdldFVzZXJSZXF1ZXN0Gg0udXNlci52MS5Vc2VyEjcKCkNyZWF0ZVVzZXISGi51c2VyLnYxLkNyZWF0ZVVzZXJSZXF1ZXN0Gg0udXNlci52MS5Vc2VyEjcKClVwZGF0ZVVzZXISGi51c2VyLnYxLlVwZGF0ZVVzZXJSZXF1ZXN0Gg0udXNlci52MS5Vc2VyEkAKCkRlbGV0ZVVzZXISGi51c2VyLnYxLkRlbGV0ZVVzZXJSZXF1ZXN0GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5QkZaRGdpdGh1Yi5jb20vU2h1LVRhbmFiZS9uZXh0LWNvbm5lY3QvZ28vaW50ZXJuYWwtYXBpL3BiL3VzZXIvdjE7dXNlcnYxYgZwcm90bzM",
    [file_google_protobuf_empty]
  );

/**
 * @generated from message user.v1.User
 */
export type User = Message<"user.v1.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string user_name = 2;
   */
  userName: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * @generated from field: string created_at = 5;
   */
  createdAt: string;
};

/**
 * Describes the message user.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> =
  /*@__PURE__*/
  messageDesc(file_user_v1_user, 0);

/**
 * @generated from message user.v1.ListUsersRequest
 */
export type ListUsersRequest = Message<"user.v1.ListUsersRequest"> & {
  /**
   * @generated from field: optional int32 page_size = 1;
   */
  pageSize?: number;

  /**
   * @generated from field: optional string page_token = 2;
   */
  pageToken?: string;
};

/**
 * Describes the message user.v1.ListUsersRequest.
 * Use `create(ListUsersRequestSchema)` to create a new message.
 */
export const ListUsersRequestSchema: GenMessage<ListUsersRequest> =
  /*@__PURE__*/
  messageDesc(file_user_v1_user, 1);

/**
 * @generated from message user.v1.ListUsersResponse
 */
export type ListUsersResponse = Message<"user.v1.ListUsersResponse"> & {
  /**
   * @generated from field: repeated user.v1.User users = 1;
   */
  users: User[];

  /**
   * @generated from field: optional string next_page_token = 2;
   */
  nextPageToken?: string;
};

/**
 * Describes the message user.v1.ListUsersResponse.
 * Use `create(ListUsersResponseSchema)` to create a new message.
 */
export const ListUsersResponseSchema: GenMessage<ListUsersResponse> =
  /*@__PURE__*/
  messageDesc(file_user_v1_user, 2);

/**
 * @generated from message user.v1.GetUserRequest
 */
export type GetUserRequest = Message<"user.v1.GetUserRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message user.v1.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export const GetUserRequestSchema: GenMessage<GetUserRequest> =
  /*@__PURE__*/
  messageDesc(file_user_v1_user, 3);

/**
 * @generated from message user.v1.CreateUserRequest
 */
export type CreateUserRequest = Message<"user.v1.CreateUserRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string user_name = 2;
   */
  userName: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: string description = 4;
   */
  description: string;
};

/**
 * Describes the message user.v1.CreateUserRequest.
 * Use `create(CreateUserRequestSchema)` to create a new message.
 */
export const CreateUserRequestSchema: GenMessage<CreateUserRequest> =
  /*@__PURE__*/
  messageDesc(file_user_v1_user, 4);

/**
 * @generated from message user.v1.UpdateUserRequest
 */
export type UpdateUserRequest = Message<"user.v1.UpdateUserRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: optional string user_name = 2;
   */
  userName?: string;

  /**
   * @generated from field: optional string email = 3;
   */
  email?: string;

  /**
   * @generated from field: optional string description = 4;
   */
  description?: string;
};

/**
 * Describes the message user.v1.UpdateUserRequest.
 * Use `create(UpdateUserRequestSchema)` to create a new message.
 */
export const UpdateUserRequestSchema: GenMessage<UpdateUserRequest> =
  /*@__PURE__*/
  messageDesc(file_user_v1_user, 5);

/**
 * @generated from message user.v1.DeleteUserRequest
 */
export type DeleteUserRequest = Message<"user.v1.DeleteUserRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message user.v1.DeleteUserRequest.
 * Use `create(DeleteUserRequestSchema)` to create a new message.
 */
export const DeleteUserRequestSchema: GenMessage<DeleteUserRequest> =
  /*@__PURE__*/
  messageDesc(file_user_v1_user, 6);

/**
 * @generated from service user.v1.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc user.v1.UserService.ListUsers
   */
  listUsers: {
    methodKind: "unary";
    input: typeof ListUsersRequestSchema;
    output: typeof ListUsersResponseSchema;
  };
  /**
   * @generated from rpc user.v1.UserService.GetUser
   */
  getUser: {
    methodKind: "unary";
    input: typeof GetUserRequestSchema;
    output: typeof UserSchema;
  };
  /**
   * @generated from rpc user.v1.UserService.CreateUser
   */
  createUser: {
    methodKind: "unary";
    input: typeof CreateUserRequestSchema;
    output: typeof UserSchema;
  };
  /**
   * @generated from rpc user.v1.UserService.UpdateUser
   */
  updateUser: {
    methodKind: "unary";
    input: typeof UpdateUserRequestSchema;
    output: typeof UserSchema;
  };
  /**
   * @generated from rpc user.v1.UserService.DeleteUser
   */
  deleteUser: {
    methodKind: "unary";
    input: typeof DeleteUserRequestSchema;
    output: typeof EmptySchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_user_v1_user, 0);
